### ISSUE TITLE
Error reading value of A/D converter

### ISSUE THREAD

**Issue by aparnasb24** [calimero-project/calimero-tools#15]
Hi All,

We have been facing some issues with the DeviceInfo of certain KNX devices. When we perform the DeviceInfo operation on it, we are facing issues with the **readActualPeiType( )** within which the **readADC( )** function is giving the error response as below:

**tuwien.auto.calimero.KNXRemoteException:  error reading value of A/D converter**

But with devices of mask versions 07B0 we are able to obtain the device info of it without any issues. But with another set of devices we are facing the above issues.

Please help us with the below issue if it something to do with certain mask versions of KNX devices.

Thank you for your help!!

**Comment by bmalinowsky** [comment]
Hi,
some devices don't support reading the A/D converter for the actual PEI type. For System B devices like 07B0 support is mandatory. You can check if the required PEI type is available.

**Comment by aparnasb24** [comment]
Thank you for quick reply. But as I see in the DeviceInfo tool of Calimero with the method **readDeviceInfo( )** 

**readActualPeiType( )** is called on every read device info operation.

Is there way using which we can call the **readActualPeiType( )** only if required PEI type is available.


Please help us if something can be done regarding this issue.


Thank you for your help!!

**Comment by bmalinowsky** [comment]
You have to be more specific. The required PEI type can also be none, or some value where no actual PEI type can be queried. If you are certain that specific device descriptors always return an error on `readActualPeiType( )`, you can put a condition before the method.

I did not limit reading the actual PEI when writing that method, because I was not certain about all combinations that might occur.
